name: Build/Deploy

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.5", "3.6", "3.7", "3.8", "pypy3.6", "pypy3.7", "pypy3.8"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Test with pytest
      run: |
        pip install -r requirements.txt
        py.test
